---
- name: Create local CA
  include_tasks: _create_local_ca.yml
  tags:
    - create_local_ca

- name: Create local cluster certificate
  include_tasks: _create_local_cluster_certificate.yml
  tags:
    - create_local_cluster_certificate

- name: APPLY - Directories    # noqa risky-file-permissions
  file:
    path: "{{ _current_directory }}"
    state: directory
  loop:
    - "/etc/ssl/private/"
  loop_control:
    loop_var: _current_directory
  when: inventory_hostname in groups['hashistack_sre']

- name: Copy certs    # noqa risky-file-permissions
  copy:
    src: "{{ _current_file.src }}"
    dest: "{{ _current_file.dest }}"
  loop:
    - src: "{{ hs_custom_ca_host_private_key }}"
      dest: "/etc/ssl/private/*.{{ public_domain }}.key"
    - src: "{{ hs_custom_ca_host_fullchain_certificate }}"
      dest: "/etc/ssl/private/*.{{ public_domain }}.fullchain.crt"
    - src: "{{ hs_custom_ca_host_certificate }}"
      dest: "/etc/ssl/private/*.{{ public_domain }}.crt"
  loop_control:
    loop_var: _current_file
  when: inventory_hostname in groups['hashistack_sre']
