---
- name: Prepare
  debug:
    msg: "Starting role preparation phase"
    verbosity: 1

- name: Uninstall existing apt packages
  apt:
    name: "getenvoy-envoy"
    state: absent

- name: Get envoy binary release
  get_url:
    url: "{{ __envoy_binary_release_url }}"
    dest: /var/cache/envoy
    mode: 0755
  tags:
    - online
