---
__hs_stage0_block_marker: >-
  # {mark}-hs-{{ role_name }}-{{ hs_stage0_name }}

__hs_stage0_terraform_module: >-
  {{ hs_stage0_provider }}_{{ hs_stage0_archi }}

__hs_stage0_terraform_module_work_dir: >-
  {{ hs_stage0_terraform_work_dir }}/{{ __hs_stage0_terraform_module }}

__hs_stage0_state: >-
  {{ (tf_action == 'destroy') | ternary('absent', 'present') }}

__hs_stage0_supported_providers:
  - "scaleway"
